// <auto-generated />
namespace Eagle.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class editedheadline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedheadline));
        
        string IMigrationMetadata.Id
        {
            get { return "202011010636463_edited-headline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
